### ISSUE TITLE
自制简易 Promise有一处错误

### ISSUE THREAD

**Issue by webproblem** [bison1994/JavaScript-Sketches#1]
自制简易 Promise 有一处错误，在 _resolve 函数中，setTimeout 应该是用错了
![image](https://user-images.githubusercontent.com/20440496/40616417-8a4a9d42-62bd-11e8-8430-807709f0db91.png)
setTimeout 应该应用在 forEach 遍历外层才有效，不然还是会同步去执行 this._resolveCallback 的遍历，应该是这样：
```javascript
// 应该是 microtask，这里仅用 setTimeout 作简化模拟
    setTimeout(() => {
        this._resolveCallback.forEach(func => {
            func(data);
        })
    }, 0)
```

**Comment by bison1994** [comment]
thanks
